import { translations } from "@/lib/lang";
import { getPreferredLanguageCookie } from "@/utils/confLanguage";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  // laguage change or set

  useEffect(() => {
    const lang = getPreferredLanguageCookie();
    setTransTo(lang || "eng");
  }, [getPreferredLanguageCookie()]);

  const [transTo, setTransTo] = useState("eng");
  const textData = translations[transTo];

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="">{textData["heroH1"]}</h1>
      </div>
    </>
  );
}
